publish_rate: 10.0
actors:
  car:
    count: 5
    initial_position: [0.0, 0.0, 0.0]
    velocity: [5.0, 0.0, 0.0]
#    acceleration: [0.0, 0.0, 0.0]
    size: [2.0, 1.0, 1.0]
  pedestrian:
    count: 10
    initial_position: [-5.0, 0.0, 0.0]
    velocity: [0.5, 0.2, 0.0]
    acceleration: [0.0, 0.0, 0.0]
    angular_velocity: [0.0, 0.0, 0.1]
    size: [0.5, 0.5, 1.7]
  cyclist:
    count: 3
    initial_position: [10.0, -5.0, 0.0]
    velocity: [-2.0, 0.5, 0.0]
#    acceleration: [0.0, 0.0, 0.0]
    size: [1.0, 0.5, 1.5]
  generic:
    count: 0
    initial_position: [ 0.0, 0.0, 0.0 ]
    velocity: [ 2.0, 0.5, 0.0 ]
    size: [ 0.5, 0.5, 1.5 ]
